package kui.gateway.api

import java.time.Instant

import cats.effect.kernel.Sync
import cats.syntax.all.*
import sttp.tapir.server.ServerEndpoint

import kui.config.{AuthType, GatewayConfig, ServerConfig}
import kui.gateway.contract.InfoEndpoints
import kui.gateway.contract.dto.{AppInfo, BuildInfoDto}
import kui.http.BasePath

/** Serving `GET /api/v1/info`.
  *
  * The interesting part is not the route, it is [[appInfo]]: a pure function from the configuration and the
  * compiled-in build facts to the document. Pure, because the rule that matters here — that nothing secret or
  * address-shaped ends up in a public document — is a rule about the *value*, and a rule about a value is
  * only testable if the value can be built without a server.
  */
object InfoRoutes {

  /** The features this deployment has switched on, by name.
    *
    * A named map rather than a set of fields, so that the shell can ask "is `cors` on?" without a version
    * check and without this DTO changing shape every milestone. Only booleans, and only things a browser has
    * a reason to branch on.
    */
  def features(gateway: GatewayConfig): Map[String, Boolean] =
    Map("cors" -> gateway.cors.enabled)

  /** The document, from the build the process was compiled from and the configuration it was started with.
    *
    * ==What is deliberately not here==
    *
    * No upstream URL, no hostname, no port, no `kid` from `gateway.principalKeys[]`. The endpoint is
    * unauthenticated, so everything in this value is public. `services` is derived from the configured
    * service map by taking its **keys** — the ids — and sorting them; the addresses those keys map to never
    * leave the process. Sorted rather than in map order so that two identical deployments produce byte-
    * identical documents, which is what makes the golden file meaningful.
    */
  def appInfo(
      server: ServerConfig,
      gateway: GatewayConfig,
      build: BuildInfoDto,
      authType: AuthType = AuthType.Disabled
  ): AppInfo =
    AppInfo(
      build = build,
      authType = authType.wire,
      // Normalised, so `"/"` and `""` — which an operator writes interchangeably — produce the same
      // document, and the shell does not have to cope with a double slash it did not create.
      basePath = BasePath.normalize(server.basePath),
      services = gateway.services.keys.map(_.value).toList.sorted,
      features = features(gateway)
    )

  /** The build this process was compiled from, as a wire type.
    *
    * `GatewayBuildInfo` is generated by `build.mill` and holds strings only, so the one conversion is the
    * timestamp. A timestamp the build could not determine parses as nothing usable, and rather than failing
    * the endpoint — which would make a missing version break the UI footer, the exact outcome GW-010 forbids
    * — it becomes the epoch, beside a `version` of `"unknown"` that says plainly what happened.
    */
  val buildInfo: BuildInfoDto =
    BuildInfoDto(
      version = GatewayBuildInfo.version,
      gitCommit = GatewayBuildInfo.gitCommit,
      gitCommitShort = GatewayBuildInfo.gitCommitShort,
      gitDirty = GatewayBuildInfo.gitDirty,
      builtAt = parseInstant(GatewayBuildInfo.builtAt),
      scalaVersion = GatewayBuildInfo.scalaVersion,
      jdkVersion = GatewayBuildInfo.jdkVersion
    )

  /** The route, unprefixed. `GatewayApi` applies `/api/v1` over the whole list. */
  def apply[F[_]: Sync](
      server: ServerConfig,
      gateway: GatewayConfig,
      authType: AuthType = AuthType.Disabled
  ): List[ServerEndpoint[Any, F]] =
    List(
      InfoEndpoints.info.serverLogicSuccess[F](_ => appInfo(server, gateway, buildInfo, authType).pure[F])
    )

  private def parseInstant(raw: String): Instant =
    scala.util.Try(Instant.parse(raw)).getOrElse(Instant.EPOCH)
}
