/**
 * The ksqlDB feature's two reads, its two writes, and the push query's stream.
 *
 * ## Why the client is cast rather than called through its generated types
 *
 * `KuiApiClient`'s methods take a path from `paths`, generated from
 * `docs/api/openapi.browser.json`. Those documents are regenerated by W8-09, *after*
 * `services/ksql` exists, so naming a ksqlDB path through the typed method is a compile error for
 * the whole of this wave. `feature-connect`'s `data.ts` reached the same wall last wave and made
 * the same cast, and the reasoning is unchanged: the cast erases the **path** check and nothing
 * else — the call still goes through the one client, so the session cookie travels, the CSRF header
 * is added to every mutation and waits for start-up if it has to, a 401 still reaches the session,
 * and nothing throws.
 *
 * It also erases the one check that would have caught a wrong path, which is why `e2e/ksql.spec.ts`
 * asks the gateway for these addresses itself and asserts what came back.
 *
 * ## Two writes, because a statement is planned before it is run (ADR-045)
 *
 * `services/ksql` implements plan→token→confirm over **free-form text**, which no other service in
 * this product does: `services/topic` plans a known operation over a named topic, and here the
 * operation is whatever somebody typed. So the browser plans every statement — not only the ones it
 * suspects — because *which statements are destructive* is the decision the service exists to make,
 * and a browser that only planned the ones it recognised would be a second, worse classifier.
 *
 * The plan is also what routes the statement: `shape` says `pull_query`, `push_query` or
 * `statement`, and a push query is **refused** at the execute address with a sentence naming the
 * stream. Asking the server rather than reading the SQL here is the same rule: two definitions of
 * "push query" is two chances to disagree, and the browser's copy would be a SQL parser in a
 * screen.
 *
 * ## The stream is a `GET`, and it is `openFetchStream` rather than `EventSource`
 *
 * A `GET` with the statement in a query parameter, because that is what `KsqlStreamEndpoint`
 * declares and why it declares it. `openFetchStream` rather than the browser's native `EventSource`
 * because `EventSource.close()` stops the *browser* listening and does not cancel the request: the
 * gateway's relay stays open, and the ksqlDB push query behind it goes on running. A push query
 * never ends by itself, so that is not a rare edge — it is what happens every time somebody
 * navigates away. `feature-messages`' `transport.ts` records the same decision for the same reason.
 */
import type { ApiError, ApiResult, KuiApiClient } from "@kui/api";
import {
  apiFailure,
  fromSection,
  openFetchStream,
  openFetchStreamWith,
  type Fetched,
  type SseError,
  type SseHandle,
  type SseSubscriber,
  type StreamTransport,
} from "@kui/kernel";

import {
  decodeObjects,
  decodePlan,
  decodeQueryHeader,
  decodeQueryRow,
  decodeResult,
  sectionOf,
  KSQL_OBJECTS_SECTION_KEY,
  KSQL_ROW_EVENT_NAME,
  Unreadable,
  type KsqlObjects,
  type KsqlRow,
  type StatementPlan,
  type StatementResult,
} from "./wire.js";

export const KSQL_OBJECTS_PATH = "/api/v1/clusters/{clusterId}/ksql/objects";
export const KSQL_PLAN_PATH = "/api/v1/clusters/{clusterId}/ksql/statements/plan";
export const KSQL_STATEMENTS_PATH = "/api/v1/clusters/{clusterId}/ksql/statements";
export const KSQL_STREAM_PATH = "/api/v1/clusters/{clusterId}/ksql/stream";

/** The query parameter the statement travels in — `KsqlStreamEndpoint.StatementParam`. */
export const STATEMENT_PARAM = "statement";

/** The cluster document, for the one fact about the deployment this screen has to ask for. */
export const CLUSTER_PATH = "/api/v1/clusters/{clusterId}";

type UncheckedAnswer =
  | { readonly ok: true; readonly value: unknown }
  | { readonly ok: false; readonly error: ApiError };

type UncheckedCall = (
  path: string,
  init: {
    readonly params: { readonly path: Record<string, string> };
    readonly body?: unknown;
  },
) => Promise<UncheckedAnswer>;

/** The sentence a document this build cannot read gets, wherever it is refused. */
export const UNREADABLE_MESSAGE =
  "KUI read the ksqlDB answer and did not recognise what was in it. This build and the ksql " +
  "service disagree about the shape of that document.";

/** A `decoding` failure, which is what `ApiError` already has for exactly this. */
function unreadable<T>(): ApiResult<T> {
  return { ok: false, error: { kind: "decoding", cause: UNREADABLE_MESSAGE } };
}

/**
 * Every stream, table, query and topic this cluster's ksqlDB named.
 *
 * The section is `not_configured` for a Kafka cluster with no `kui.clusters.<n>.ksql.url` at all,
 * and it arrives with a 200 — a deployment that never intended to run ksqlDB is not a broken one,
 * and ADR-032's rule for that is a sentence rather than a red panel.
 */
export async function fetchObjects(
  api: KuiApiClient,
  clusterId: string,
): Promise<Fetched<KsqlObjects>> {
  const get = api.get as unknown as UncheckedCall;
  const answer = await get(KSQL_OBJECTS_PATH, { params: { path: { clusterId } } });
  if (!answer.ok) return apiFailure(answer.error);

  const section = sectionOf(answer.value, KSQL_OBJECTS_SECTION_KEY);
  if (section === undefined) {
    return {
      kind: "failed",
      message:
        "KUI could not read the ksqlDB object list: the server's answer carried no " +
        `'${KSQL_OBJECTS_SECTION_KEY}' section.`,
      code: "UNREADABLE_BODY",
    };
  }

  const decoded = fromSection(section, (payload) => payload);
  if (decoded.kind !== "ready" && decoded.kind !== "stale") return decoded;

  const objects = decodeObjects(decoded.value);
  /*
   * The refusal that stops this package repeating wave 5's worst defect. A payload this build
   * cannot read is reported as unread, never as a ksqlDB with no streams — the second sentence is
   * one an operator acts on, by going and looking for streams that are already there.
   */
  if (objects === Unreadable) {
    return { kind: "failed", message: UNREADABLE_MESSAGE, code: "UNREADABLE_BODY" };
  }

  return decoded.kind === "stale"
    ? { kind: "stale", value: objects, reason: decoded.reason }
    : { kind: "ready", value: objects };
}

/**
 * What running this statement would do.
 *
 * Called for **every** statement, including the harmless ones. `StatementPlanDto`'s own scaladoc
 * says why: a screen that only knew how to plan the dangerous ones would have to decide which those
 * are, and that is the decision this service exists to make.
 */
export async function planStatement(
  api: KuiApiClient,
  clusterId: string,
  statement: string,
): Promise<ApiResult<StatementPlan>> {
  const post = api.post as unknown as UncheckedCall;
  const answer = await post(KSQL_PLAN_PATH, {
    params: { path: { clusterId } },
    // `token: null` and not an omitted field: `StatementRequestDto` is one shape for both phases,
    // and a plan is never confirming anything.
    body: { statement, token: null },
  });
  if (!answer.ok) return { ok: false, error: answer.error };

  const plan = decodePlan(answer.value);
  return plan === Unreadable ? unreadable<StatementPlan>() : { ok: true, value: plan };
}

/**
 * Runs one statement that finishes.
 *
 * The statement sent is the **plan's** canonicalised text rather than whatever is in the editor at
 * the moment the confirmation is pressed. `KsqlPlanToken.verify` refuses a token whose statement is
 * not character-for-character the one being applied, which is how ADR-045's guarantee survives an
 * endpoint that has to carry the statement as well as the token — and sending the editor's current
 * text would break exactly that guarantee the moment somebody typed while a dialogue was open.
 */
export async function runStatement(
  api: KuiApiClient,
  clusterId: string,
  plan: StatementPlan,
): Promise<ApiResult<StatementResult>> {
  const post = api.post as unknown as UncheckedCall;
  const answer = await post(KSQL_STATEMENTS_PATH, {
    params: { path: { clusterId } },
    body: { statement: plan.statement, token: plan.token ?? null },
  });
  if (!answer.ok) return { ok: false, error: answer.error };

  const result = decodeResult(answer.value);
  return result === Unreadable ? unreadable<StatementResult>() : { ok: true, value: result };
}

/**
 * How a push query is opened.
 *
 * A type rather than a bare function reference so that `KsqlScreen` can take one as a prop. The
 * product passes {@link openPushQuery} and a case passes a stream it drives itself — which is the
 * only way to put the screen into `streaming`, `ended` and `interrupted` and assert what each of
 * them draws. Without the seam those three states are reachable only from a real network, and
 * ADR-056's three hardest decisions would be gated by nothing but `model.test.ts`.
 */
export type PushQueryOpener = (
  clusterId: string,
  statement: string,
  subscriber: PushQuerySubscriber,
) => SseHandle;

/** Where a push query's frames arrive, and what a caller does with them. */
export interface PushQuerySubscriber {
  /** The column names, once, as soon as ksqlDB accepted the query. */
  readonly onColumns: (columns: readonly string[]) => void;
  readonly onRow: (row: KsqlRow) => void;
  readonly onError: (error: SseError) => void;
  readonly onDone?: (() => void) | undefined;
}

/**
 * The address of one push query.
 *
 * Built here rather than in the component so that the browser and `e2e/ksql.spec.ts` build it the
 * same way, and so that the encoding is in one place: a `SELECT` carries `*`, `=`, `'` and spaces,
 * all of which change meaning in a query string if they are not escaped.
 */
export function pushQueryAddress(clusterId: string, statement: string): string {
  const path = KSQL_STREAM_PATH.replace("{clusterId}", encodeURIComponent(clusterId));
  return `${path}?${new URLSearchParams({ [STATEMENT_PARAM]: statement }).toString()}`;
}

/**
 * Opens a push query and delivers its frames.
 *
 * The four shared ADR-035 events are the kernel's — `done` ends the stream, `error` ends it with
 * the server's own envelope, `heartbeat` proves it is alive, `phase` carries the columns — so this
 * subscriber lists only the row event, and the kernel refuses a subscriber that lists a shared one.
 *
 * A frame this build cannot read is a `decode` failure, which is **not** terminal: one malformed
 * row must not end a query that is otherwise delivering good ones. That is the kernel's rule and
 * the message browser follows it too.
 */
export function openPushQuery(
  clusterId: string,
  statement: string,
  subscriber: PushQuerySubscriber,
  transport?: StreamTransport | undefined,
  resolveUrl: (path: string) => string = (path) => path,
): SseHandle {
  const url = resolveUrl(pushQueryAddress(clusterId, statement));
  /*
   * The transport is a seam and the default is the real one.
   *
   * Without it this function's body — which event name it registers, how it parses a frame, which
   * failures it forwards — is reachable from no case at all: `KsqlScreen` takes a
   * `PushQueryOpener`, so every screen case replaces this whole function. Measured rather than
   * assumed: renaming the event to `"ksql-row"` left 74/74 green before the seam existed, and the
   * name is the one thing on this wire that a golden already pins. `openFetchStreamWith` is the
   * kernel's own seam for exactly this, and `feature-messages` uses the same pair.
   */
  const subscription: SseSubscriber<KsqlRow> = {
    events: [KSQL_ROW_EVENT_NAME],
    decode: (_event, data) => {
      const payload = parse(data);
      if (payload === Unreadable) return { ok: false, cause: "the frame was not JSON" };
      const row = decodeQueryRow(payload);
      return row === Unreadable
        ? { ok: false, cause: "the frame carried no values this build could read" }
        : { ok: true, value: row };
    },
    onEvent: (row) => subscriber.onRow(row),
    onPhase: (data) => {
      /* Reuses the wire's own decoder rather than parsing here, so there is one definition of
         what a phase frame looks like. A phase that does not decode is dropped rather than
         reported: it is the column list, and failing a query because the headings could not be
         read would be the tail wagging the dog — the rows still arrive and still draw, under
         positional headings. */
      const payload = parse(data);
      if (payload === Unreadable) return;
      const columns = decodeQueryHeader(payload);
      if (columns !== Unreadable) subscriber.onColumns(columns);
    },
    onError: (error) => subscriber.onError(error),
    onDone: () => subscriber.onDone?.(),
  };

  return transport === undefined
    ? openFetchStream({ url, method: "GET" }, subscription)
    : openFetchStreamWith(transport, subscription);
}

function parse(data: string): unknown | Unreadable {
  try {
    return JSON.parse(data) as unknown;
  } catch {
    return Unreadable;
  }
}

/** What the deployment says about writing to this cluster at all. */
export interface ClusterWriteState {
  readonly readOnly: boolean;
}

/**
 * Whether this cluster is registered read-only.
 *
 * A fact about the deployment rather than about the principal, and the two are asked separately:
 * `writeBlockedReason` puts the read-only sentence first because it is the one an operator can do
 * nothing about. `feature-topics` reads the same document through the same endpoint; this is a
 * second reader of one fact and not a second source for it.
 *
 * A failure here answers "not read-only" rather than disabling the editor, which is the same choice
 * `useKui().permits` documents: refusing every write on a fact KUI does not have would put a
 * screenful of refusals in front of every reader for the length of one request, and the server is
 * the authority either way.
 */
export async function fetchClusterWriteState(
  api: KuiApiClient,
  clusterId: string,
): Promise<Fetched<ClusterWriteState>> {
  const get = api.get as unknown as UncheckedCall;
  const answer = await get(CLUSTER_PATH, { params: { path: { clusterId } } });
  if (!answer.ok) return apiFailure(answer.error);
  const body = answer.value as { readonly cluster?: { readonly readOnly?: boolean } } | null;
  return { kind: "ready", value: { readOnly: body?.cluster?.readOnly === true } };
}
